// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSXx2B0JmTHOmN7EF5YTuPU9dBssSBMkU',
    appId: '1:630572068835:web:c3ca47b3103e3c0e1b7ad6',
    messagingSenderId: '630572068835',
    projectId: 'apex-55499',
    authDomain: 'apex-55499.firebaseapp.com',
    storageBucket: 'apex-55499.firebasestorage.app',
    measurementId: 'G-ZY3YDSRN7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2rjyeCh-PMMACb0-elvDsA7q3w_iYwKo',
    appId: '1:630572068835:android:5551bf72d7b39feb1b7ad6',
    messagingSenderId: '630572068835',
    projectId: 'apex-55499',
    storageBucket: 'apex-55499.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_yWGudmBeVKH5iNab4StMJhbVRl23vEw',
    appId: '1:630572068835:ios:f3fcc080aa080d491b7ad6',
    messagingSenderId: '630572068835',
    projectId: 'apex-55499',
    storageBucket: 'apex-55499.firebasestorage.app',
    iosBundleId: 'com.apex.apex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_yWGudmBeVKH5iNab4StMJhbVRl23vEw',
    appId: '1:630572068835:ios:f3fcc080aa080d491b7ad6',
    messagingSenderId: '630572068835',
    projectId: 'apex-55499',
    storageBucket: 'apex-55499.firebasestorage.app',
    iosBundleId: 'com.apex.apex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSXx2B0JmTHOmN7EF5YTuPU9dBssSBMkU',
    appId: '1:630572068835:web:5825196a2a358fd81b7ad6',
    messagingSenderId: '630572068835',
    projectId: 'apex-55499',
    authDomain: 'apex-55499.firebaseapp.com',
    storageBucket: 'apex-55499.firebasestorage.app',
    measurementId: 'G-VRQC42VX54',
  );

}